#####################################################################
# Global defaults

# Default design type selected (value should be one of available design types)
defaultDesignType = "Custom"

# Default delivery selected (value should be one of available deliveries)
defaultDelivery = "Pick-up"


#####################################################################
# Design Types (format: designTypes."<design type>")
# Total price will be calculated as:
#    base price + round(amount) * step price
[designTypes."Custom"]
price = 270
stepPrice = 40

[designTypes."Semi-custom"]
price = 160
stepPrice = 40


#####################################################################
# Product variants (format: products."<product name>".variants."<variant name>")
# There are two ways you can specify the printing price:
#   * For every single copy (e.g. Guestbook)
#       Use: price = 2
#   * For every 10/50/100/150 copies (e.g. Name card)
#       Use: price = [20, 40, 61, 77]

[products."Save the Date card".variants."One-sided"]
price = [25, 45, 66, 82]

[products."Save the Date card".variants."Double-sided"]
price = [35, 55, 76, 92]

[products."Save the Date card".variants."Folded"]
price = [45, 65, 86, 102]

[products."Save the Date card".variants."Vellum paper"]
price = [35, 55, 76, 92]

[products."Invitation".variants."One-sided"]
price = [35, 55, 75, 90]

[products."Invitation".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Invitation".variants."Folded"]
price = [58, 78, 98, 113]

[products."Invitation".variants."Trifold"]
price = [65, 85, 105, 115]

[products."Invitation".variants."Vellum paper"]
price = [45, 65, 85, 100]

[products."Invitation + info".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Invitation + info".variants."Folded"]
price = [58, 78, 98, 113]

[products."Invitation + info".variants."Trifold"]
price = [65, 85, 105, 115]

[products."Info card".variants."One-sided"]
price = [35, 55, 75, 90]

[products."Info card".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Info card".variants."Folded"]
price = [58, 78, 98, 113]

[products."Info card + map".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Info card + map".variants."Folded"]
price = [58, 78, 98, 113]

[products."Map".variants."One-sided"]
price = [35, 55, 75, 90]

[products."Table numbers".variants."One-sided"]
price = [16, 31, 51, 71]

[products."Table numbers".variants."Double-sided"]
price = [20, 35, 55, 75]

[products."Name card".variants."One-sided"]
price = [27, 47, 67, 87]

[products."Name card".variants."Folded/standing"]
price = [30, 50, 70, 90]

[products."Name card".variants."Tag"]
price = [29, 49, 69, 89]

[products."Name card".variants."Round corners"]
price = [29, 49, 69, 89]

[products."Name card".variants."Vellum paper"]
price = [29, 49, 69, 89]

[products."Menu".variants."One-sided"]
price = [35, 55, 75, 90]

[products."Menu".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Menu".variants."Folded"]
price = [58, 78, 98, 113]

[products."Menu".variants."Vellum paper"]
price = [45, 65, 85, 100]

[products."Program".variants."One-sided"]
price = [35, 55, 75, 90]

[products."Program".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Program".variants."Folded"]
price = [58, 78, 98, 113]

[products."Menu + program".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Menu + program".variants."Folded"]
price = [58, 78, 98, 113]

[products."Church program".variants."One-sided"]
price = [35, 55, 75, 90]

[products."Church program".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Church program".variants."Folded"]
price = [58, 78, 98, 113]

[products."Bride or Groom game".variants."One-sided"]
price = [35, 55, 75, 90]

[products."Bingo".variants."One-sided"]
price = [35, 60, 80, 95]

[products."Stickers".variants."Square/rectangular"]
price = [25, 45, 65, 75]

[products."Stickers".variants."Round"]
price = [30, 50, 70, 85]

[products."Stickers".variants."Address labels, white or any other color"]
price = [30, 50, 70, 85]

[products."Stickers".variants."Address labels, transparent"]
price = [30, 50, 70, 85]

[products."Poster/sign".variants."A4"]
price = 8

[products."Poster/sign".variants."A3"]
price = 18

[products."Poster/sign".variants."A2"]
price = 22

[products."Poster/sign".variants."50x70"]
price = 28

[products."Poster/sign".variants."A1"]
price = 34

[products."Seating chart".variants."A3"]
price = 18

[products."Seating chart".variants."A2"]
price = 22

[products."Seating chart".variants."50x70"]
price = 28

[products."Seating chart".variants."A1"]
price = 34

[products."Guestbook".variants."30x20, 30 pages"]
price = 75

[products."Guestbook".variants."20x20, 30 pages"]
price = 65

[products."Guestbook".variants."20x20, wooden, 60 pages, ready-made"]
price = 57

[products."Guestbook".variants."20x20, wooden, 60 pages, custom"]
price = 69

[products."Wedding wishes cards".variants."One-sided"]
price = [20, 40, 61, 77]

[products."Thank you card".variants."One-sided with photo"]
price = [35, 55, 75, 90]

[products."Thank you card".variants."Double-sided with photo"]
price = [45, 65, 85, 100]

[products."Thank you card".variants."Folded with photo"]
price = [58, 78, 98, 113]

[products."Any other card".variants."One-sided"]
price = [35, 55, 75, 90]

[products."Any other card".variants."Double-sided"]
price = [45, 65, 85, 100]

[products."Any other card".variants."Folded"]
price = [58, 78, 98, 113]

[products."Any other card".variants."Trifold"]
price = [65, 85, 105, 115]


#####################################################################
# Product ordering (format: products."<product name>")
# The bigger the weight the lower the product be in the list.
# For non-specified products here weight is 0. If weight is the same
# then products are ordered by the name.
[productOrdering."Any other card"]
weight = 99


#####################################################################
# Additional products (configuration is the same as for products section)
[additionalProducts."Envelope".variants."105x148, A6"]
price = 0.60

[additionalProducts."Envelope".variants."90x140, textured"]
price = 0.55

[additionalProducts."Envelope".variants."130x184, textured"]
price = 0.80

[additionalProducts."Envelope".variants."120x180, textured"]
price = 0.80

[additionalProducts."Wax seals".variants."Bronze"]
price = 0.90

[additionalProducts."Wax seals".variants."Forest green"]
price = 0.90

[additionalProducts."Wax seals".variants."White"]
price = 0.90

[additionalProducts."Wax seals".variants."Pastel pink"]
price = 0.90

[additionalProducts."Wax seals".variants."Golden"]
price = 0.90

[additionalProducts."Wax seals".variants."Silver"]
price = 0.90

[additionalProducts."Wax seals".variants."Navy blue"]
price = 0.90

[additionalProducts."Wax seals".variants."Burgundy"]
price = 0.90

[additionalProducts."Wax seals".variants."Custom colour"]
price = 0.95


#####################################################################
# Delivery options (format: delivery."<delivery name>")
# Delivery price will be added to the total order price.
[delivery."Post"]
price =  9

[delivery."Pick-up"]
price =  0
