#####################################################################
# Global defaults

# Default design type selected (value should be one of available design types)
defaultDesignType = "Yksilöllinen"

# Default delivery selected (value should be one of available deliveries)
defaultDelivery = "Noutopiste"


#####################################################################
# Design Types (format: designTypes."<design type>")
# Total price will be calculated as:
#    base price + round(amount) * step price
[designTypes."Semi-custom"]
price = 165
stepPrice = 40

[designTypes."Custom"]
price = 280
stepPrice = 40


#####################################################################
# Product variants (format: products."<product name>".variants."<variant name>")
# There are two ways you can specify the printing price:
#   * For every single copy (e.g. Guestbook)
#       Use: price = 2
#   * For every 10/50/100/150 copies (e.g. Name card)
#       Use: price = [20, 40, 61, 77]

[products."Save the Date kortti".variants."Yksipuolinen"]
price = [30, 50, 70, 85]

[products."Save the Date kortti".variants."Kaksipuolinen"]
price = [40, 60, 80, 95]

[products."Save the Date kortti".variants."Taitettu"]
price = [50, 70, 90, 105]

[products."Save the Date kortti".variants."Vellum/läpinäkyva paperi"]
price = [40, 60, 80, 95]

[products."Kutsu".variants."Yksipuolinen"]
price = [45, 65, 85, 100]

[products."Kutsu".variants."Kaksipuolinen"]
price = [50, 70, 90, 105]

[products."Kutsu".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Kutsu".variants."Kolmiosainen"]
price = [70, 90, 110, 120]

[products."Kutsu".variants."Vellum/läpinäkyva paperi"]
price = [50, 70, 90, 105]

[products."Kutsu + info kortti".variants."Kaksipuolinen"]
price = [50, 70, 90, 105]

[products."Kutsu + info kortti".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Kutsu + info kortti".variants."Kolmiosainen"]
price = [70, 90, 110, 120]

[products."Info kortti".variants."Yksipuolinen"]
price = [45, 65, 85, 100]

[products."Info kortti".variants."Kaksipuolinen"]
price = [50, 70, 90, 105]

[products."Info kortti".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Info kortti + kartta".variants."Kaksipuolinen"]
price = [50, 70, 90, 105]

[products."Info kortti + kartta".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Kartta".variants."Yksipuolinen"]
price = [45, 65, 85, 100]

[products."Pöytänumerot".variants."Yksipuolinen"]
price = [16, 31, 51, 71]

[products."Pöytänumerot".variants."Kaksipuolinen"]
price = [20, 35, 55, 75]

[products."Nimikortti".variants."Yksipuolinen"]
price = [27, 47, 67, 87]

[products."Nimikortti".variants."Taitettu"]
price = [35, 55, 75, 95]

[products."Nimikortti".variants."Tuotelappu/reiällä"]
price = [30, 50, 70, 90]

[products."Nimikortti".variants."Pyöristetyt kulmat"]
price = [30, 50, 70, 90]

[products."Nimikortti".variants."Vellum/läpinäkyva paperi"]
price = [35, 55, 75, 95]

[products."Menu".variants."Yksipuolinen"]
price = [45, 65, 85, 100]

[products."Menu".variants."Kaksipuolinen"]
price = [50, 70, 90, 105]

[products."Menu".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Menu".variants."Vellum/läpinäkyva paperi"]
price = [50, 70, 90, 105]

[products."Ohjelma".variants."Yksipuolinen"]
price = [50, 70, 90, 105]

[products."Ohjelma".variants."Kaksipuolinen"]
price = [65, 85, 105, 115]

[products."Ohjelma".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Menu + ohjelma".variants."Kaksipuolinen"]
price = [50, 70, 90, 105]

[products."Menu + ohjelma".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Kirkko - ohjelma".variants."Yksipuolinen"]
price = [45, 65, 85, 100]

[products."Kirkko - ohjelma".variants."Kaksipuolinen"]
price = [50, 70, 90, 105]

[products."Kirkko - ohjelma".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Morsian tai sulhanen peli".variants."Yksipuolinen"]
price = [45, 65, 85, 100]

[products."Bingo".variants."Yksipuolinen"]
price = [45, 65, 85, 100]

[products."Tarrat".variants."Neliö/suorakulmio"]
price = [25, 45, 65, 75]

[products."Tarrat".variants."Ympyrä"]
price = [30, 50, 70, 85]

[products."Tarrat".variants."Osoitetarrat, värilliset tai valkoiset"]
price = [30, 50, 70, 85]

[products."Tarrat".variants."Osoitetarrat, läpinäkyvat"]
price = [30, 50, 70, 85]

[products."Juliste/kyltti".variants."A4"]
price = 8

[products."Juliste/kyltti".variants."A3"]
price = 18

[products."Juliste/kyltti".variants."A2"]
price = 22

[products."Juliste/kyltti".variants."50x70"]
price = 28

[products."Juliste/kyltti".variants."A1"]
price = 34

[products."Istumajärjestys".variants."A3"]
price = 18

[products."Istumajärjestys".variants."A2"]
price = 22

[products."Istumajärjestys".variants."50x70"]
price = 28

[products."Istumajärjestys".variants."A1"]
price = 34

[products."Vieraskirja".variants."30x20, 30 sivua"]
price = 75

[products."Vieraskirja".variants."20x20, 30 sivua"]
price = 65

[products."Vieraskirja".variants."20x20, puinen, 60 sivua, valmis malli"]
price = 57

[products."Vieraskirja".variants."20x20, wooden, 60 sivua, yksilöllinen"]
price = 69

[products."Terveiset hääpärille lappuset".variants."Yksipuolinen"]
price = [20, 40, 61, 77]

[products."Kiitos kortti".variants."Yksipuolinen, omasta kuvasta"]
price = [45, 65, 85, 100]

[products."Kiitos kortti".variants."Kaksipuolinen, omasta kuvasta"]
price = [50, 70, 90, 105]

[products."Kiitos kortti".variants."Taitettu, omasta kuvasta"]
price = [65, 85, 105, 115]

[products."Muut kortit".variants."Yksipuolinen"]
price = [45, 65, 85, 100]

[products."Muut kortit".variants."Kaksipuolinen"]
price = [50, 70, 90, 105]

[products."Muut kortit".variants."Taitettu"]
price = [65, 85, 105, 115]

[products."Muut kortit".variants."Kolmiosainen"]
price = [70, 90, 110, 120]


#####################################################################
# Product ordering (format: products."<product name>")
# The bigger the weight the lower the product be in the list.
# For non-specified products here weight is 0. If weight is the same
# then products are ordered by the name.
[productOrdering."Muut kortit"]
weight = 99


#####################################################################
# Additional products (configuration is the same as for products section)
[additionalProducts."Kirjekuori".variants."105x148, A6"]
price = 0.60

[additionalProducts."Kirjekuori".variants."90x140, tekstuurinen"]
price = 0.55

[additionalProducts."Kirjekuori".variants."125x175, värillinen"]
price = 0.80

[additionalProducts."Kirjekuori".variants."120x180, tekstuurinen"]
price = 0.80

[additionalProducts."Vahasinetti".variants."Pronssi"]
price = 0.90

[additionalProducts."Vahasinetti".variants."Vihreä"]
price = 0.90

[additionalProducts."Vahasinetti".variants."Valkoinen"]
price = 0.90

[additionalProducts."Vahasinetti".variants."Vaaleanpunainen"]
price = 0.90

[additionalProducts."Vahasinetti".variants."Kultainen"]
price = 0.90

[additionalProducts."Vahasinetti".variants."Hopeinen"]
price = 0.90

[additionalProducts."Vahasinetti".variants."Laivastonsininen"]
price = 0.90

[additionalProducts."Vahasinetti".variants."Viininpunainen"]
price = 0.90

[additionalProducts."Vahasinetti".variants."Custom colour"]
price = 0.95

#####################################################################
# Delivery options (format: delivery."<delivery name>")
# Delivery price will be added to the total order price.
[delivery."Posti"]
price =  9

[delivery."Noutopiste"]
price =  0
